from data.publisher import CALCULATOR_FAMILIES
from generators.publisher_pages import render_calculator_page


def build_concrete_calculator_page() -> str:
    family = next(item for item in CALCULATOR_FAMILIES if item["slug"] == "concrete-calculator")
    form_html = """<div class="toggle-row" role="tablist" aria-label="Concrete mode"><button class="mode-toggle is-active" data-mode="slab" type="button">Slab</button><button class="mode-toggle" data-mode="footing" type="button">Footing</button><button class="mode-toggle" data-mode="post" type="button">Post holes</button></div><div class="toggle-row units-row" role="tablist" aria-label="Units"><button class="unit-toggle is-active" data-unit="metric" type="button">Metric</button><button class="unit-toggle" data-unit="imperial" type="button">Imperial</button></div><form id="concrete-form" class="calculator-form"><div class="field-grid"><label><span>Length</span><input id="length" type="number" min="0" step="0.01" value="3"></label><label><span>Width</span><input id="width" type="number" min="0" step="0.01" value="2"></label><label><span>Depth</span><input id="depth" type="number" min="0" step="0.01" value="0.1"></label><label><span>Number of holes</span><input id="count" type="number" min="1" step="1" value="6"></label><label><span>Waste allowance (%)</span><input id="waste" type="number" min="0" step="1" value="10"></label><label><span>Price per m³</span><input id="price-per-m3" type="number" min="0" step="0.01" value="140"></label></div><button class="btn btn-primary btn-block" type="submit">Calculate concrete</button></form>"""
    result_html = """<div class="result-kicker">Estimated result</div><h2 class="result-main">Enter your measurements</h2><p class="result-sub">You will see the concrete volume and rough material cost here.</p><div class="currency-pills" role="tablist" aria-label="Currency"><button class="currency-pill is-active" data-currency="GBP" type="button">GBP £</button><button class="currency-pill" data-currency="USD" type="button">USD $</button><button class="currency-pill" data-currency="EUR" type="button">EUR €</button></div><div class="result-breakdown" id="result-breakdown"></div>"""
    return render_calculator_page(slug=family["slug"], title=family["name"], description=family["meta_description"], intro=family["intro"], form_html=form_html, result_html=result_html, script_name="concrete-calculator.js")
