from data.publisher import CALCULATOR_FAMILIES
from generators.publisher_pages import render_calculator_page


def build_decking_calculator_page() -> str:
    family = next(item for item in CALCULATOR_FAMILIES if item["slug"] == "decking-calculator")
    form_html = """<div class="toggle-row units-row" role="tablist" aria-label="Units"><button class="unit-toggle is-active" data-unit="metric" type="button">Metric</button><button class="unit-toggle" data-unit="imperial" type="button">Imperial</button></div><form id="decking-form" class="calculator-form"><div class="field-grid"><label><span>Deck length</span><input id="length" type="number" min="0" step="0.01" value="5"></label><label><span>Deck width</span><input id="width" type="number" min="0" step="0.01" value="3"></label><label><span>Board width</span><input id="board-width" type="number" min="0" step="1" value="140"></label><label><span>Board length</span><input id="board-length" type="number" min="0" step="0.01" value="4.8"></label><label><span>Joist spacing</span><input id="joist-spacing" type="number" min="0" step="1" value="400"></label><label><span>Waste allowance (%)</span><input id="waste" type="number" min="0" step="1" value="10"></label><label><span>Price per board</span><input id="price-per-board" type="number" min="0" step="0.01" value="18"></label><label><span>Price per joist</span><input id="price-per-joist" type="number" min="0" step="0.01" value="14"></label></div><button class="btn btn-primary btn-block" type="submit">Calculate decking</button></form>"""
    result_html = """<div class="result-kicker">Estimated result</div><h2 class="result-main">Enter your measurements</h2><p class="result-sub">You will see the board count, joist estimate, rough material cost, and decision outputs here.</p><div class="currency-pills" role="tablist" aria-label="Currency"><button class="currency-pill is-active" data-currency="GBP" type="button">GBP</button><button class="currency-pill" data-currency="USD" type="button">USD</button><button class="currency-pill" data-currency="EUR" type="button">EUR</button></div><div class="result-breakdown" id="result-breakdown"></div>"""
    return render_calculator_page(slug=family["slug"], title=family["name"], description=family["meta_description"], intro=family["intro"], form_html=form_html, result_html=result_html, script_name="decking-calculator.js")
