from data.publisher import CALCULATOR_FAMILIES
from generators.publisher_pages import render_calculator_page


def build_fence_calculator_page() -> str:
    family = next(item for item in CALCULATOR_FAMILIES if item["slug"] == "fence-calculator")
    form_html = """<div class="toggle-row units-row" role="tablist" aria-label="Units"><button class="unit-toggle is-active" data-unit="metric" type="button">Metric</button><button class="unit-toggle" data-unit="imperial" type="button">Imperial</button></div><form id="fence-form" class="calculator-form"><div class="field-grid"><label><span>Total fence length</span><input id="length" type="number" min="0" step="0.01" value="10"></label><label><span>Panel width</span><input id="panel-width" type="number" min="0" step="0.01" value="1.8"></label><label><span>Post depth</span><input id="post-depth" type="number" min="0" step="0.01" value="0.6"></label><label><span>Waste allowance (%)</span><input id="waste" type="number" min="0" step="1" value="5"></label><label><span>Price per panel</span><input id="price-per-panel" type="number" min="0" step="0.01" value="25"></label><label><span>Price per post</span><input id="price-per-post" type="number" min="0" step="0.01" value="18"></label><label><span>Concrete per post (m3)</span><input id="concrete-per-post" type="number" min="0" step="0.01" value="0.03"></label><label><span>Price per m3 concrete</span><input id="price-per-concrete" type="number" min="0" step="0.01" value="140"></label></div><button class="btn btn-primary btn-block" type="submit">Calculate fencing</button></form>"""
    result_html = """<div class="result-kicker">Estimated result</div><h2 class="result-main">Enter your measurements</h2><p class="result-sub">You will see the panel count, supporting items, rough material cost, and wider estimate view here.</p><div class="currency-pills" role="tablist" aria-label="Currency"><button class="currency-pill is-active" data-currency="GBP" type="button">GBP</button><button class="currency-pill" data-currency="USD" type="button">USD</button><button class="currency-pill" data-currency="EUR" type="button">EUR</button></div><div class="result-breakdown" id="result-breakdown"></div>"""
    return render_calculator_page(slug=family["slug"], title=family["name"], description=family["meta_description"], intro=family["intro"], form_html=form_html, result_html=result_html, script_name="fence.js")
