from data.publisher import CALCULATOR_FAMILIES
from generators.publisher_pages import render_calculator_page


def build_flooring_calculator_page() -> str:
    family = next(item for item in CALCULATOR_FAMILIES if item["slug"] == "flooring-calculator")
    form_html = """<div class="toggle-row" role="tablist" aria-label="Flooring mode"><button class="mode-toggle is-active" data-mode="laminate" type="button">Laminate</button><button class="mode-toggle" data-mode="wood" type="button">Wood</button><button class="mode-toggle" data-mode="vinyl" type="button">Vinyl plank</button></div><div class="toggle-row units-row" role="tablist" aria-label="Units"><button class="unit-toggle is-active" data-unit="metric" type="button">Metric</button><button class="unit-toggle" data-unit="imperial" type="button">Imperial</button></div><form id="flooring-form" class="calculator-form"><div class="field-grid"><label><span id="room-length-label">Room length (m)</span><input id="room-length" type="number" min="0" step="0.01" value="4.4"></label><label><span id="room-width-label">Room width (m)</span><input id="room-width" type="number" min="0" step="0.01" value="3.6"></label><label><span>Board width (mm)</span><input id="plank-width" type="number" min="0" step="1" value="192"></label><label><span>Board length (mm)</span><input id="plank-length" type="number" min="0" step="1" value="1285"></label><label><span>Pack coverage (m2 per pack)</span><input id="pack-coverage" type="number" min="0" step="0.01" value="1.84"></label><label><span>Waste allowance (%)</span><input id="waste" type="number" min="0" step="1" value="8"></label><label><span>Price per pack</span><input id="price-per-pack" type="number" min="0" step="0.01" value="29.99"></label></div><p class="form-note">Starter defaults assume a straightforward room, standard plank format, and a practical allowance for cut loss plus safer whole-pack rounding.</p><button class="btn btn-primary btn-block" type="submit">Calculate flooring packs</button></form>"""
    result_html = """<div class="result-kicker">Estimated result</div><h2 class="result-main">Enter your measurements</h2><p class="result-sub">You will see the room area, pack count, approximate board count, and wider buying guidance here.</p><div class="currency-pills" role="tablist" aria-label="Currency"><button class="currency-pill is-active" data-currency="GBP" type="button">GBP</button><button class="currency-pill" data-currency="USD" type="button">USD</button><button class="currency-pill" data-currency="EUR" type="button">EUR</button></div><div class="result-breakdown" id="result-breakdown"></div><p class="result-context" id="result-context"></p>"""
    return render_calculator_page(slug=family["slug"], title=family.get("meta_title", family["name"]), description=family["meta_description"], intro=family["intro"], form_html=form_html, result_html=result_html, script_name="flooring-calculator.js")
