from data.publisher import CALCULATOR_FAMILIES
from generators.publisher_pages import render_calculator_page


def build_tile_calculator_page() -> str:
    family = next(item for item in CALCULATOR_FAMILIES if item["slug"] == "tile-calculator")
    form_html = """<div class="toggle-row" role="tablist" aria-label="Tile surface"><button class="mode-toggle is-active" data-mode="floor" type="button">Floor</button><button class="mode-toggle" data-mode="wall" type="button">Wall</button></div><div class="toggle-row units-row" role="tablist" aria-label="Units"><button class="unit-toggle is-active" data-unit="metric" type="button">Metric</button><button class="unit-toggle" data-unit="imperial" type="button">Imperial</button></div><form id="tile-form" class="calculator-form"><div class="field-grid"><label><span>Project length</span><input id="length" type="number" min="0" step="0.01" value="3"></label><label><span>Project width</span><input id="width" type="number" min="0" step="0.01" value="2.5"></label><label><span>Tile length</span><input id="tile-length" type="number" min="0" step="1" value="600"></label><label><span>Tile width</span><input id="tile-width" type="number" min="0" step="1" value="300"></label><label><span>Tiles per box</span><input id="tiles-per-box" type="number" min="1" step="1" value="8"></label><label><span>Waste allowance (%)</span><input id="waste" type="number" min="0" step="1" value="10"></label><label><span>Price per box</span><input id="price-per-box" type="number" min="0" step="0.01" value="24.99"></label></div><button class="btn btn-primary btn-block" type="submit">Calculate tiles</button></form>"""
    result_html = """<div class="result-kicker">Estimated result</div><h2 class="result-main">Enter your measurements</h2><p class="result-sub">You will see the tile count, box total, rough material cost, and decision outputs here.</p><div class="currency-pills" role="tablist" aria-label="Currency"><button class="currency-pill is-active" data-currency="GBP" type="button">GBP</button><button class="currency-pill" data-currency="USD" type="button">USD</button><button class="currency-pill" data-currency="EUR" type="button">EUR</button></div><div class="result-breakdown" id="result-breakdown"></div>"""
    return render_calculator_page(slug=family["slug"], title=family["name"], description=family["meta_description"], intro=family["intro"], form_html=form_html, result_html=result_html, script_name="tile-calculator.js")
